# fly.toml app configuration file generated for foodwiz on 2023-09-26T10:25:13-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "foodwiz"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
